### ISSUE TITLE
argument option

### ISSUE THREAD

**Issue by sec13b** [Muhammad207010/ssh-bruteforce#1]
arg.add_option("-u", "--usname", dest= "username", help= "enter username of target ip e.g. <root>@192.168.1.1")
    arg.add_option("-i", "--ipaddr", dest= "target_ip", help= "enter target ip e.g. root@<192.168.1.1>")
    arg.add_option("-w", "--wordlist", dest= "wordlist", help= "enter your wordlist")

can add model how to ?

i use : ython3 ssh-bruteforce.py  -i iplist.txt -u user.txt -w pwd.txt

iplist = list with ip`s i try 20 ip
user : root (1 username)
pwd: list with password

**Comment by Muhammad207010** [comment]
I added these options except **ip-list**.
thanks for your suggestions.
enjoy
